# Generated by Django 4.2.1 on 2023-05-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Popular women'},
        ),
    ]
